version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/transactions_db
      REDIS_URL: redis://redis:6379/0
      API_KEY: your_secret_api_key
  celery:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/transactions_db
      REDIS_URL: redis://redis:6379/0
      API_KEY: your_secret_api_key
volumes:
  db_data:
